# Change these first
owner: streamloots # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: "WWW | Landing"
    url: https://www.streamloots.com
  - name: "WWW | Streamers"
    url: https://www.streamloots.com/streamers
  - name: API
    url: https://api.streamloots.com/heartbeat
  - name: Widgets
    url: https://widgets.streamloots.com/heartbeat

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Streamloots Status Site
  introTitle: Latest Updates
  introMessage: Site to announce any maintenance and the current status of Streamloots
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
